
export const GITHUB_CLEAR_USERS = "GITHUB_CLEAR_USERS";
export const GITHUB_GET_REPOS = "GITHUB_GET_REPOS";
export const GITHUB_GET_USER = "GITHUB_GET_USER";
export const GITHUB_SEARCH_USERS = "GITHUB_SEARCH_USERS";
export const GITHUB_SET_LOADING = "GITHUB_SET_LOADING";